services:
  spring-image:
    container_name: springboot-image-cont
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/album_app
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootdbpassword
    volumes:
      - /home/oscar/Desktop/LSR/album-app/pictures:/pictures
    networks:
      - springboot-network

  mysql:
    image: mysql:8
    container_name: mysql-image-cont
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootdbpassword
      MYSQL_DATABASE: album_app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-network

  react-image:
    container_name: react-image-cont
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    depends_on:
      - spring-image
    networks:
      - springboot-network
    stdin_open: true
    tty: true
    command: npm start


networks:
  springboot-network:

volumes:
  mysql_data:
